# Generated by Django 3.0.6 on 2020-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=4000)),
                ('biolink', models.CharField(max_length=500)),
                ('author_born', models.CharField(max_length=1000)),
                ('author_location', models.CharField(max_length=1000)),
            ],
        ),
    ]
